AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 Bucket Template

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-cfn-bucket-paul  # Replace with your unique bucket name
      
Outputs:
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
